name: CI

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-quality:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: A job to check my code quality
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@master
      with:
        # Token to checkout the repository.
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Access key on Code Inspector
        code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        # Secret key on Code Inspector
        code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        # Minimum grade. Valid options are EXCELLENT, GOOD, NEUTRAL, WARNING, CRITICAL. Leave blank to ignore.
        min_quality_grade: 'WARNING'
        # Minimum quality score from 0 (worst) to 100 (best)
        min_quality_score: '50'
        # Maximum defect rate per line of code (e.g. 0.01 for 1 defect per 100 lines of code). Leave 0 to ignore.
        max_defects_rate: '0.0001'
        # Maximum number of complex functions rate (e.g. number of complex functions / number of functions). Leave 0 to ignore.
        max_complex_functions_rate: '0.0001'
        # Maximum number of long functions rate (e.g. number of long functions / number of functions). Leave 0 to ignore.
        max_long_functions_rate: '0.0001'
        # Project on code inspector. Will use the preferences of this analysis. Leave blank and no preferences are used
        project_name: '' 
        # Timeout before giving up (in case analysis takes too long). Default is 10 minutes
        max_timeout_sec: '600'
